# Copyright (C) 2013 Sony Mobile Communication
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#### THE FILE IS GENERATED BY SCRIPT SO DO NOT MODIFY IT MANUALLY! ####

PRODUCT_COPY_FILES += \
    device/sony/c2105/rootdir/root/fstab.sony:root/fstab.sony \
    device/sony/c2105/rootdir/root/init.sony.rc:root/init.sony.rc \
    device/sony/c2105/rootdir/root/init.sony.usb.rc:root/init.sony.usb.rc \
    device/sony/c2105/rootdir/root/logo.rle:root/logo.rle \
    device/sony/c2105/rootdir/root/ueventd.sony.rc:root/ueventd.sony.rc \
    device/sony/c2105/rootdir/system/etc/audio_policy.conf:system/etc/audio_policy.conf \
    device/sony/c2105/rootdir/system/etc/g.prop:system/etc/g.prop \
    device/sony/c2105/rootdir/system/etc/gps.conf:system/etc/gps.conf \
    device/sony/c2105/rootdir/system/etc/media_codecs.xml:system/etc/media_codecs.xml \
    device/sony/c2105/rootdir/system/etc/media_profiles.xml:system/etc/media_profiles.xml \
    device/sony/c2105/rootdir/system/etc/nfcee_access.xml:system/etc/nfcee_access.xml \
    device/sony/c2105/rootdir/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    device/sony/c2105/rootdir/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    device/sony/c2105/rootdir/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    device/sony/c2105/rootdir/system/etc/permissions/features.xml:system/etc/permissions/features.xml \
    device/sony/c2105/rootdir/system/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
    device/sony/c2105/rootdir/system/etc/snd_soc_msm/snd_soc_msm_Sitar:system/etc/snd_soc_msm/snd_soc_msm_Sitar \
    device/sony/c2105/rootdir/system/etc/thermald.conf:system/etc/thermald.conf \
    device/sony/c2105/rootdir/system/etc/vold.fstab:system/etc/vold.fstab \
    device/sony/c2105/rootdir/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    device/sony/c2105/rootdir/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    device/sony/c2105/rootdir/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    device/sony/c2105/rootdir/system/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so \
    device/sony/c2105/rootdir/system/lib/libRSSupport.so:system/lib/libRSSupport.so \
    device/sony/c2105/rootdir/system/lib/libfilterframework_jni.so:system/lib/libfilterframework_jni.so \
    device/sony/c2105/rootdir/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    device/sony/c2105/rootdir/system/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp_jni.so \
    device/sony/c2105/rootdir/system/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
    device/sony/c2105/rootdir/system/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
    device/sony/c2105/rootdir/system/lib/libjni_t13n_shared_engine.so:system/lib/libjni_t13n_shared_engine.so \
    device/sony/c2105/rootdir/system/lib/libjni_unbundled_latinimegoogle.so:system/lib/libjni_unbundled_latinimegoogle.so \
    device/sony/c2105/rootdir/system/lib/libmoviemaker-jni.so:system/lib/libmoviemaker-jni.so \
    device/sony/c2105/rootdir/system/lib/libnetjni.so:system/lib/libnetjni.so \
    device/sony/c2105/rootdir/system/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
    device/sony/c2105/rootdir/system/lib/libplus_jni_v8.so:system/lib/libplus_jni_v8.so \
    device/sony/c2105/rootdir/system/lib/librs.antblur.so:system/lib/librs.antblur.so \
    device/sony/c2105/rootdir/system/lib/librs.antblur_constant.so:system/lib/librs.antblur_constant.so \
    device/sony/c2105/rootdir/system/lib/librs.antblur_drama.so:system/lib/librs.antblur_drama.so \
    device/sony/c2105/rootdir/system/lib/librs.drama.so:system/lib/librs.drama.so \
    device/sony/c2105/rootdir/system/lib/librs.film_base.so:system/lib/librs.film_base.so \
    device/sony/c2105/rootdir/system/lib/librs.fixedframe.so:system/lib/librs.fixedframe.so \
    device/sony/c2105/rootdir/system/lib/librs.grey.so:system/lib/librs.grey.so \
    device/sony/c2105/rootdir/system/lib/librs.image_wrapper.so:system/lib/librs.image_wrapper.so \
    device/sony/c2105/rootdir/system/lib/librs.retrolux.so:system/lib/librs.retrolux.so \
    device/sony/c2105/rootdir/system/lib/librsjni.so:system/lib/librsjni.so \
    device/sony/c2105/rootdir/system/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    device/sony/c2105/rootdir/system/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    device/sony/c2105/rootdir/system/lib/libvideochat_jni.so:system/lib/libvideochat_jni.so \
    device/sony/c2105/rootdir/system/lib/libwebp_android.so:system/lib/libwebp_android.so \
    device/sony/c2105/rootdir/system/lib/libwebrtc_audio_coding.so:system/lib/libwebrtc_audio_coding.so \
    device/sony/c2105/rootdir/system/usr/keychars/pmic8xxx_pwrkey.kcm:system/usr/keychars/pmic8xxx_pwrkey.kcm \
    device/sony/c2105/rootdir/system/usr/keylayout/cyttsp3-i2c.kl:system/usr/keylayout/cyttsp3-i2c.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/keypad_8960.kl:system/usr/keylayout/keypad_8960.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/msm8930-sitar-snd-card_Button_Jack.kl:system/usr/keylayout/msm8930-sitar-snd-card_Button_Jack.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/pmic8xxx_pwrkey.kl:system/usr/keylayout/pmic8xxx_pwrkey.kl \
    device/sony/c2105/rootdir/system/usr/keylayout/simple_remote_appkey.kl:system/usr/keylayout/simple_remote_appkey.kl \
    device/sony/c2105/rootdir/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    device/sony/c2105/rootdir/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg \
    device/sony/c2105/rootdir/system/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf \
    device/sony/c2105/rootdir/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    device/sony/c2105/rootdir/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    device/sony/c2105/rootdir/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    device/sony/c2105/rootdir/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    device/sony/c2105/rootdir/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn \
    device/sony/c2105/rootdir/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    device/sony/c2105/rootdir/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    device/sony/c2105/rootdir/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model \
    device/sony/c2105/rootdir/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    device/sony/c2105/rootdir/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    device/sony/c2105/rootdir/system/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword \
    device/sony/c2105/rootdir/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols \
    device/sony/c2105/rootdir/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist \
    device/sony/c2105/rootdir/system/usr/srec/en-US/hotword.config:system/usr/srec/en-US/hotword.config \
    device/sony/c2105/rootdir/system/usr/srec/en-US/hotword_classifier:system/usr/srec/en-US/hotword_classifier \
    device/sony/c2105/rootdir/system/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer \
    device/sony/c2105/rootdir/system/usr/srec/en-US/hotword_prompt.txt:system/usr/srec/en-US/hotword_prompt.txt \
    device/sony/c2105/rootdir/system/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols \
    device/sony/c2105/rootdir/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    device/sony/c2105/rootdir/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
    device/sony/c2105/rootdir/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer \
    device/sony/c2105/rootdir/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer \
    device/sony/c2105/rootdir/system/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map \
    device/sony/c2105/rootdir/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    device/sony/c2105/rootdir/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm \
    device/sony/c2105/rootdir/system/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist \
